language: go
go:
  - "1.11.x"

go_import_path: github.com/phogolabs/parcello

env:
  - GO111MODULE=on

before_script:
  - mysql -e 'CREATE DATABASE gom;'
  - psql -c 'CREATE DATABASE gom;' -U postgres

install:
  - go get github.com/onsi/ginkgo/...
  - go build ./...

script:
  - ginkgo -r -v -covermode=atomic

after_success:
  - script/cover.sh
  - bash <(curl -s https://codecov.io/bash)